image: "hseeberger/scala-sbt:11.0.4_1.3.3_2.13.1"

variables:
  SBT_OPTS: "-Dsbt.global.base=sbt-cache/sbtboot -Dsbt.boot.directory=sbt-cache/boot -Dsbt.ivy.home=sbt-cache/ivy -Dsbt.coursier.home=sbt-cache/coursier"
  COURSIER_CACHE: sbt-cache/coursier

cache:
  key: "$CI_BUILD_REF_NAME"
  untracked: true
  paths:
    - "sbt-cache/sbtboot"
    - "sbt-cache/boot"
    - "sbt-cache/ivy/cache"
    - "sbt-cache/coursier"

stages:
  - test

test:
  variables:
    GOOGLE_APPLICATION_CREDENTIALS: "/tmp/google-application-credentials.json"
  before_script:
    - base64 -d $GCLOUD_SECRET >> $GOOGLE_APPLICATION_CREDENTIALS
  script:
    - sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck it:scalafmtCheck test it:test
  after_script:
    - rm $GCLOUD_SECRET $GOOGLE_APPLICATION_CREDENTIALS
